### PR TITLE
Enable windows

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
```
    -- Building for: Visual Studio 15 2017 Win64
    CMake Error at CMakeLists.txt:3 (project):
      Generator

        Visual Studio 15 2017 Win64

      does not support platform specification, but platform

        x64

      was specified.
```

**Comment by srmnitc** [comment]
@jan-janssen Thanks for the help - a quick question: If I make some changes to `setup.py`, do I have to make a release to test the recipe here?

**Comment by srmnitc** [comment]
I released a new version of pyscal where I set up testing on windows using azure pipelines and everything seems to work.

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by srmnitc** [comment]
Strange! it seems to be the same problem. Let me check again. Thanks!

**Comment by jan-janssen** [comment]
I have to admit I am no windows expert, but at least in the current stage we try to support all three platforms.

**Comment by srmnitc** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@srmnitc I created a patch to fix the windows installation - Can you take a look?

**Comment by srmnitc** [comment]
This looks good! Thanks a lot @jan-janssen

**Comment by jan-janssen** [comment]
Can you add the patch to the official pascal code?

**Comment by srmnitc** [comment]
Yes I will do this!

**Pull request merged**
