### PR TITLE
add h5py to dependencies

### PR DESCRIPTION
**Pull request by srmnitc**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by srmnitc** [comment]
@jan-janssen Adding h5py as a dependency to prepare for the release of pyscal - 2.10.8. Could you verify how did this is okay?

**Comment by jan-janssen** [comment]
Please bump the build number: 

> Checklist
> 
> * [ ]  Bumped the build number (if the version is unchanged)

In addition it seems h5py is not yet compatible with `pypy` 
https://github.com/conda-forge/h5py-feedstock/pull/70

**Comment by srmnitc** [comment]
> 
> 
> Please bump the build number:
> 
> > Checklist
> > 
> > * [ ]   Bumped the build number (if the version is unchanged)
> 
> In addition it seems h5py is not yet compatible with `pypy`
> [conda-forge/h5py-feedstock#70](https://github.com/conda-forge/h5py-feedstock/pull/70)

Okay thanks, we will keep it open for the moment then. Thanks!

**Comment by jan-janssen** [comment]
@conda-forge-admin restart ci

**Comment by jan-janssen** [comment]
@conda-forge-admin restart ci

**Comment by srmnitc** [comment]
@jan-janssen Actually I think we can just close this. On second thought, I would actually drop the h5py codebit that I have. Thanks a lot  for your efforts!

**Comment by jan-janssen** [comment]
That is fine with me as well ;-)

**Pull request closed without merging**
